import { Handler } from '@netlify/functions';

export const handler: Handler = async (event) => {
  const headers = {
    'Access-Control-Allow-Origin': '*',
    'Access-Control-Allow-Headers': 'Content-Type, Authorization',
    'Access-Control-Allow-Methods': 'POST, OPTIONS',
    'Content-Type': 'application/json',
  };

  if (event.httpMethod === 'OPTIONS') {
    return { statusCode: 200, headers, body: '' };
  }

  if (event.httpMethod !== 'POST') {
    return {
      statusCode: 405,
      headers,
      body: JSON.stringify({ error: 'Method not allowed' }),
    };
  }

  try {
    const body = JSON.parse(event.body || '{}');
    const { format, sopData } = body;

    // For now, return a simple text export
    // In production, you'd generate actual PDF/DOCX files
    
    if (format === 'md') {
      const markdown = generateMarkdown(sopData);
      return {
        statusCode: 200,
        headers: {
          ...headers,
          'Content-Type': 'text/markdown',
          'Content-Disposition': `attachment; filename="${sopData.title || 'SOP'}.md"`,
        },
        body: markdown,
      };
    }

    // For PDF/DOCX, return a placeholder
    return {
      statusCode: 501,
      headers,
      body: JSON.stringify({ 
        error: 'PDF/DOCX export not yet implemented',
        message: 'Use Markdown export for now'
      }),
    };
  } catch (error) {
    console.error('Export error:', error);
    return {
      statusCode: 500,
      headers,
      body: JSON.stringify({ error: 'Export failed' }),
    };
  }
};

function generateMarkdown(sopData: any): string {
  return `# ${sopData.title || 'Standard Operating Procedure'}

**Version:** ${sopData.version || '1.0'}
**Created:** ${new Date().toLocaleDateString()}

## Overview

${sopData.overview || 'No overview provided'}

## Purpose

${sopData.purpose || 'No purpose provided'}

## Scope

${sopData.scope || 'No scope provided'}

## Procedure

${sopData.steps?.map((step: any, i: number) => 
  `### Step ${i + 1}: ${step.title || 'Untitled Step'}

${step.description || 'No description'}

${step.substeps?.map((sub: any, j: number) => 
  `${i + 1}.${j + 1}. ${sub}`
).join('\n') || ''}`
).join('\n\n') || 'No steps provided'}

## Inputs

${sopData.inputs?.map((input: string) => `- ${input}`).join('\n') || 'No inputs specified'}

## Outputs

${sopData.outputs?.map((output: string) => `- ${output}`).join('\n') || 'No outputs specified'}

## Notes

${sopData.notes || 'No additional notes'}

---

*Generated by AI Voice SOP Agent*
`;
}
